version: '2'
services:
  proxy:
    build:
      context: ./envoy
    volumes:
      - ./envoy/service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "80:80"
      - "8001:8001"
  authz:
    build:
      context: ./authz
    networks:
      envoymesh:
        aliases:
          - authz
    ports:
      - "9091:9091"
  service:
    build:
      context: ./app
    networks:
      envoymesh:
        aliases:
          - service
    ports:
      - "8080:8080"
  
  redis:
    image: redis:5-alpine
    networks:
      envoymesh:
        aliases:
          - redis
    ports:
      - 5432:5432

  ratelimit:
    build:
      context: ./ratelimit
    command: /bin/ratelimit
    depends_on:
      - redis
    ports:
      - 8081:8081
      - 6070:6070
    volumes:
      - ./config:/data
    networks:
      envoymesh:
        aliases:
          - ratelimit
    environment:
      - USE_STATSD=false
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=ratelimit

networks:
  envoymesh: {}